### PR TITLE
Increase delay between jokes

### PR DESCRIPTION
**Pull request by danielbreves**
:suspect:

So it's less distracting, easier to read and not as bandwidth intensive :)

/cc @zendesklabs/quokka

### CODE REVIEW

**Comment by itirkarp** [comment]
:+1:

**Comment by svizzari** [comment]
Chuck Norris would actually *decrease* the delay y'know

On Wednesday, May 13, 2015, Prakriti Mateti <notifications@github.com>
wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zendesklabs/chucknorris_app/pull/5#issuecomment-101551770>
> .
>


-- 
Stefan Vizzari
Snr. Software Engineer - APAC

Zendesk <http://www.zendesk.com/>
Twitter: @s_vizzari  |  Skype: zendesk.svizzari | Phone: +61 407 511 960

**Comment by svizzari** [comment]
:+1: even tho chuck wouldn't like it

On Wednesday, May 13, 2015, Stefan Vizzari <svizzari@zendesk.com> wrote:

> Chuck Norris would actually *decrease* the delay y'know
>
> On Wednesday, May 13, 2015, Prakriti Mateti <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> [image: :+1:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/zendesklabs/chucknorris_app/pull/5#issuecomment-101551770>
>> .
>>
>
>
> --
> Stefan Vizzari
> Snr. Software Engineer - APAC
>
> Zendesk <http://www.zendesk.com/>
> Twitter: @s_vizzari  |  Skype: zendesk.svizzari | Phone: +61 407 511 960
>
>

-- 
Stefan Vizzari
Snr. Software Engineer - APAC

Zendesk <http://www.zendesk.com/>
Twitter: @s_vizzari  |  Skype: zendesk.svizzari | Phone: +61 407 511 960

**Comment by danielbreves** [comment]
@svizzari :suspect:

**Comment by maximeprades** [comment]
haha. 

just deployed it live now

**Comment by sandlerr** [comment]
pretty sure you can make this a CORS request

**Comment by svizzari** [comment]
> http://api.icndb.com/jokes/random

Yep, the icndb is cors enabled.

Then it will look like there is almost no traffic through the proxy ;)

**Pull request merged**
